<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("test3424");
?>            <?
            $APPLICATION->IncludeComponent(
	"bitrix:iblock.element.add.form", 
	"portfolio_form", 
	array(
		"IBLOCK_TYPE" => "content",
		"IBLOCK_ID" => "8",
		"STATUS_NEW" => "2",
		"LIST_URL" => "",
		"USE_CAPTCHA" => "N",
		"USER_MESSAGE_EDIT" => "",
		"USER_MESSAGE_ADD" => "",
		"DEFAULT_INPUT_SIZE" => "30",
		"RESIZE_IMAGES" => "Y",
		"PROPERTY_CODES" => array(
			0 => "NAME",
			1 => "DETAIL_TEXT",
			2 => "DETAIL_PICTURE",
			3 => "84",
			4 => "258",
			5 => "85",
			6 => "86",
			7 => "87",
			8 => "88",
			9 => "89",
			10 => "90",
			11 => "91",
			12 => "260",
			13 => "389",
			14 => "355",
		),
		"PROPERTY_CODES_REQUIRED" => array(
			0 => "NAME",
			1 => "DETAIL_PICTURE",
			2 => "84",
			3 => "258",
			4 => "85",
			5 => "86",
			6 => "88",
			7 => "89",
			8 => "90",
			9 => "91",
			10 => "260",
		),
		"GROUPS" => array(
			0 => "1",
			1 => "5",
		),
		"STATUS" => array(
			0 => "2",
		),
		"ELEMENT_ASSOC" => "PROPERTY_ID",
		"ELEMENT_ASSOC_PROPERTY" => "",
		"MAX_USER_ENTRIES" => "100000",
		"MAX_LEVELS" => "100000",
		"LEVEL_LAST" => "Y",
		"MAX_FILE_SIZE" => "0",
		"PREVIEW_TEXT_USE_HTML_EDITOR" => "Y",
		"DETAIL_TEXT_USE_HTML_EDITOR" => "Y",
		"SEF_MODE" => "Y",
		"SEF_FOLDER" => "/",
		"CUSTOM_TITLE_NAME" => "Название объекта",
		"CUSTOM_TITLE_TAGS" => "",
		"CUSTOM_TITLE_DATE_ACTIVE_FROM" => "",
		"CUSTOM_TITLE_DATE_ACTIVE_TO" => "",
		"CUSTOM_TITLE_IBLOCK_SECTION" => "",
		"CUSTOM_TITLE_PREVIEW_TEXT" => "",
		"CUSTOM_TITLE_PREVIEW_PICTURE" => "",
		"CUSTOM_TITLE_DETAIL_TEXT" => "",
		"CUSTOM_TITLE_DETAIL_PICTURE" => ""
	),
	false
);
            ?><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>